Add VictoriaMetrics monitoring system
awesome-foss/awesome-sysadmin pull request #376
Opened 2022-02-13 16:56 UTC by valyala

### Application name / category
[awesometool](https://example.com) / Devops

### Source URL
https://github.example.com/repo

### why it is awesome
This tool is so awesome because it allows me to do awesome things in my
awesome corp, especially when I use it to manage awesome othersoftware.

2022-09-05 18:50 UTC, KieranRobson requested changes
https://github.com/awesome-foss/awesome-sysadmin/blob/master/.github/CONTRIBUTING.md

Please order your contribution to be alphabetical within the list

2022-09-14 12:18 UTC, valyala commented
> Please order your contribution to be alphabetical within the list

Done

2022-09-14 12:22 UTC, KieranRobson approved these changes
LGTM

2022-09-14 22:09 UTC, nodiscc approved these changes

2022-09-14 22:09 UTC, merged