Add Dockovpn to VPN list
awesome-foss/awesome-sysadmin pull request #393
Opened 2022-08-17 21:25 UTC by alekslitvinenk

### Dockovpn / VPN
[Dockovpn](https://dockovpn.io) / Devops

### Source URL
https://github.com/dockovpn/dockovpn

### why it is awesome
Dockovpn is an out of the box dockerized OpenVPN compatible server, which starts in just a few seconds and runs forever.

2022-09-05 18:02 UTC, KieranRobson requested changes
https://github.com/awesome-foss/awesome-sysadmin/blob/master/.github/CONTRIBUTING.md

Please order your contribution alphabetically

2022-09-05 19:33 UTC, KieranRobson approved these changes

2022-09-06 10:28 UTC, nodiscc requested changes

2022-09-17 16:20 UTC, alekslitvinenk commented on README.md
> +* [Dockovpn](https://dockovpn.io) - Out of the box stateless dockerized openvpn compartible server which starts in less than 2 seconds.
Fixed

2022-12-05 22:24 UTC, xrat commented on README.md
> +* [Dockovpn](https://dockovpn.io) - Out-of-the-box stateless dockerized OpenVPN-compartible server which starts in less than 2 seconds.
s/compartible/compatible/

2023-03-01 13:33 UTC, nodiscc requested changes
Hi @alekslitvinenk , since https://github.com/awesome-foss/awesome-sysadmin/pull/459 we have new contribution guidelines in place, could you please take some time to answer the following questions as best you can? Thanks

- **Why is it awesome?**
- **Have you used it? For how long?**
- **Is this in a personal or professional setup?**
- **How many devices/users/services/... do you manage with it?**
- **Biggest pros/cons compared to other solutions?**

2023-03-02 18:27 UTC, alekslitvinenk commented
@nodiscc I updated PR message

2023-03-12 13:33 UTC, nodiscc approved these changes

2023-03-15 04:42 UTC, Technetium1 approved these changes

2023-03-20 16:59 UTC, merged