SSO Keycloak
awesome-foss/awesome-sysadmin pull request #418
Opened 2022-10-19 21:48 UTC by darkdragon-001

Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [x] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at [awesome-selfhosted](https://github.com/awesome-foss/awesome-sysadmin)
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items (see #409)
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

### Why it is awesome

This provider is so awesome because it allows you to maintain a single account but provide many independent services.

2022-10-20 11:07 UTC, fbartels commented
It is probably easier to put the change from this pr and https://github.com/awesome-foss/awesome-sysadmin/pull/419/ and https://github.com/awesome-foss/awesome-sysadmin/pull/420/ in a single pr. As soon as one of them is merged there will be a merge conflict in the other two prs that would need fixing/rebase.

2022-10-21 14:37 UTC, nodiscc requested changes

2022-10-21 14:37 UTC, nodiscc commented on README.md
> +- [KeyCloak](https://www.keycloak.org) - Open Source Identity and Access Management ([Source Code](https://github.com/keycloak/keycloak)) Apache-2.0 `Java`
```suggestion
- [KeyCloak](https://www.keycloak.org) - Open Source Identity and Access Management ([Source Code](https://github.com/keycloak/keycloak)) `Apache-2.0 `Java`
```

2022-10-21 14:40 UTC, nodiscc approved these changes
thanks

2022-10-21 14:40 UTC, darkdragon-001 commented
I noticed you were missing the closing mark and only added the opening one.

2022-10-21 14:41 UTC, darkdragon-001 commented
I fixed it.

2022-11-04 16:30 UTC, merged