Add Status to Monitoring software
awesome-foss/awesome-sysadmin pull request #452
Opened 2023-01-28 23:39 UTC by dani3l0

Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [x] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at [awesome-selfhosted](https://github.com/awesome-foss/awesome-sysadmin)
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

### Why it is awesome

Status is a lightweight system monitoring app written in Python having only one dependency. It provides a fair amount of hardware information like CPU, physical memory, network and storage. Reported to work flawlessly on most Intel and AMD PCs, and even on Raspberry Pis. This makes Status a perfect solution for small homeservers.

2023-01-30 14:17 UTC, nodiscc requested changes

2023-01-30 14:17 UTC, nodiscc commented on README.md
> +- [Status](https://gitlab.com/dani3l0/status) - Simple and lightweight system monitoring tool with a pleasant web interface. ([Demo](https://status-ksk5.onrender.com/)) `MIT` `Python`
```suggestion
- [Status](https://gitlab.com/dani3l0/status) - Simple and lightweight system monitoring tool for small homeservers with a pleasant web interface. ([Demo](https://status-ksk5.onrender.com/)) `MIT` `Python`
```

2023-01-30 19:46 UTC, dani3l0 commented
This description sounds much better.

2023-03-01 13:28 UTC, nodiscc requested changes
Hi @dani3l0, since https://github.com/awesome-foss/awesome-sysadmin/pull/459 we have new contribution guidelines in place, could you please take some time to answer the following questions as best you can? Thanks

- **Have you used it? For how long?**
- **Is this in a personal or professional setup?**
- **How many devices/users/services/... do you manage with it?**
- **Biggest pros/cons compared to other solutions?**

2023-03-01 18:47 UTC, dani3l0 commented
Updated!

2023-03-05 11:06 UTC, dani3l0 commented
Hey, just moved Status to GitHub and fixed merge conflicts. Was the latter necessary?

2023-03-05 15:10 UTC, nodiscc approved these changes

2023-03-12 13:28 UTC, merged