Add backrest to README.md
awesome-foss/awesome-sysadmin pull request #597
Opened 2024-12-05 01:02 UTC by garethgeorge

Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [X] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [X] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts). _software is my own, but has a good ecosystem ~1700 stars as of PR_.
- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at [awesome-selfhosted](https://awesome-selfhosted.net)
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

Please take some time to answer the following questions as best you can:

- **Why is it awesome?**

Backrest is gaining significant popularity in the selfhosted community (particularly r/selfhosted) and builds on established reliable tools e.g. restic for storage. The significant contribution is that, prior to backrest, there was not a widely accepted webUI for configuring restic and automating backup operations. Backrest makes this process easy and makes restic significantly more approachable, especially for self-hosted users.

- **Have you used it? For how long?**

Backrest has been available for just over a year.

- **Is this in a personal or professional setup?**

Backrest is primarily self-hosted but I am aware of some professional installs and educational institutions using the software.

- **How many devices/users/services/... do you manage with it?**

To answer slightly orthoganally since I maintain the software , the install stats are 

~250k downloads on docker hub and ~15k bare metal installs via direct download.

- **Biggest pros/cons compared to other solutions?**

Backrest is not designed to be a desktop native UI, there are some other projects that attempt this e.g. NpBackup or Restic-Browser. Backrest specifically targets web deployments (though it can also be installed on laptop devices and windows machines) where your browser is the primary interface client.

2025-01-04 15:27 UTC, Ki-er requested changes

2025-01-04 15:27 UTC, Ki-er commented on README.md
> +- [Backrest](https://garethgeorge.github.io/backrest/) - Backrest is a web UI and orchestrator for restic backup. ([Source Code](https://github.com/garethgeorge/backrest))
```suggestion
- [Backrest](https://garethgeorge.github.io/backrest/) - Backrest is a web UI and orchestrator for restic backup. ([Source Code](https://github.com/garethgeorge/backrest)) `GPL-3.0` `Docker/Go`
```

2025-01-17 05:41 UTC, Ki-er approved these changes

2025-03-31 18:52 UTC, Technetium1 approved these changes

2025-03-31 18:54 UTC, merged